import { ClientsData } from "../types/ClientsData";

export const clients: ClientsData[] = [{
    'BAIRRO': "Jardim das Amoreiras",
    'CEP': "76543-210",
    'CNAE PRINCIPAL CODIGO': "8219999",
    'CNAE PRINCIPAL DESCRICAO': "Atividades de serviços prestados principalmente às empresas",
    'CNPJ': "99999999000100",
    'COMPLEMENTO': "SALA 4",
    'DATA ABERTURA': "20/03/2013",
    'DDD': "51",
    'EMAIL': "contato@servicoexemplo.com",
    'LOGRADOURO': "Avenida das Empresas, 321",
    'MUNICIPIO': "Porto Alegre",
    'NOME FANTASIA': "Serviços Empresariais Brasil",
    'NUMERO': "321",
    'RAZAO SOCIAL': "Empresa de Serviços Exemplo Ltda",
    'SETOR': "Serviços Empresariais",
    'STATUS': "ATIVA",
    'TELEFONE': "(51) 9876-5432",
    'TIPO LOGRADOURO': "Avenida",
    'UF': "RS",
    'ID': '1',
        },{
    'BAIRRO': "Vila dos Artistas",
    'CEP': "23456-789",
    'CNAE PRINCIPAL CODIGO': "9001900",
    'CNAE PRINCIPAL DESCRICAO': "Atividades de produção cinematográfica, de vídeos e de programas de televisão",
    'CNPJ': "11111111000123",
    'COMPLEMENTO': "ESTÚDIO 3",
    'DATA ABERTURA': "08/12/2010",
    'DDD': "21",
    'EMAIL': "contato@estudioexemplo.com",
    'LOGRADOURO': "Rua do Audiovisual, 456",
    'MUNICIPIO': "Rio de Janeiro",
    'NOME FANTASIA': "Estúdio Criativo",
    'NUMERO': "456",
    'RAZAO SOCIAL': "Estúdio de Produção Exemplo Ltda",
    'SETOR': "Produção Audiovisual",
    'STATUS': "ATIVA",
    'TELEFONE': "(21) 5555-9876",
    'TIPO LOGRADOURO': "Rua",
    'UF': "RJ",
    'ID': '2',
    },{
    'BAIRRO': "Bela Vista",
    'CEP': "98765-432",
    'CNAE PRINCIPAL CODIGO': "5813000",
    'CNAE PRINCIPAL DESCRICAO': "Edição de jornais",
    'CNPJ': "44444444000100",
    'COMPLEMENTO': "ANDAR 12",
    'DATA ABERTURA': "12/06/2015",
    'DDD': "31",
    'EMAIL': "contato@editoraexemplo.com",
    'LOGRADOURO': "Avenida da Imprensa, 789",
    'MUNICIPIO': "Belo Horizonte",
    'NOME FANTASIA': "Editora Notícias do Dia",
    'NUMERO': "789",
    'RAZAO SOCIAL': "Editora Exemplo S.A.",
    'SETOR': "Editora",
    'STATUS': "ATIVA",
    'TELEFONE': "(31) 9876-5432",
    'TIPO LOGRADOURO': "Avenida",
    'UF': "MG",
    'ID': '3',
    },{
    'BAIRRO': "Vila das Artes",
    'CEP': "12345-678",
    'CNAE PRINCIPAL CODIGO': "9001302",
    'CNAE PRINCIPAL DESCRICAO': "Atividades de museus e de conservação do patrimônio histórico",
    'CNPJ': "77777777000100",
    'COMPLEMENTO': "SALA 1",
    'DATA ABERTURA': "30/07/2011",
    'DDD': "11",
    'EMAIL': "contato@museuexemplo.com",
    'LOGRADOURO': "Rua dos Artistas, 123",
    'MUNICIPIO': "São Paulo",
    'NOME FANTASIA': "Museu Cultural",
    'NUMERO': "123",
    'RAZAO SOCIAL': "Museu Exemplo Ltda",
    'SETOR': "Cultura",
    'STATUS': "ATIVA",
    'TELEFONE': "(11) 5555-4321",
    'TIPO LOGRADOURO': "Rua",
    'UF': "SP",
    'ID': '4',
    },{
    'BAIRRO': "Centro Empresarial",
    'CEP': "34567-890",
    'CNAE PRINCIPAL CODIGO': "7020400",
    'CNAE PRINCIPAL DESCRICAO': "Atividades de consultoria em gestão empresarial",
    'CNPJ': "22222222000100",
    'COMPLEMENTO': "ANDAR 5",
    'DATA ABERTURA': "15/09/2014",
    'DDD': "47",
    'EMAIL': "contato@consultoriaexemplo.com",
    'LOGRADOURO': "Avenida da Consultoria, 789",
    'MUNICIPIO': "Joinville",
    'NOME FANTASIA': "Consultoria de Negócios Estratégicos",
    'NUMERO': "789",
    'RAZAO SOCIAL': "Consultoria Exemplo S.A.",
    'SETOR': "Consultoria Empresarial",
    'STATUS': "ATIVA",
    'TELEFONE': "(47) 9876-5432",
    'TIPO LOGRADOURO': "Avenida",
    'UF': "SC",
    'ID': '5',
    },{
    'BAIRRO': "Vila das Ciências",
    'CEP': "65432-109",
    'CNAE PRINCIPAL CODIGO': "7210700",
    'CNAE PRINCIPAL DESCRICAO': "Pesquisa e desenvolvimento em biotecnologia",
    'CNPJ': "33333333000100",
    'COMPLEMENTO': "LABORATÓRIO 2",
    'DATA ABERTURA': "04/11/2012",
    'DDD': "81",
    'EMAIL': "contato@biotecexemplo.com",
    'LOGRADOURO': "Avenida da Inovação, 321",
    'MUNICIPIO': "Recife",
    'NOME FANTASIA': "Laboratório de Biotecnologia Avançada",
    'NUMERO': "321",
    'RAZAO SOCIAL': "Biotec Exemplo Ltda",
    'SETOR': "Biotecnologia",
    'STATUS': "ATIVA",
    'TELEFONE': "(81) 5555-1234",
    'TIPO LOGRADOURO': "Avenida",
    'UF': "PE",
    'ID': '6',
    },{
    'BAIRRO': "Vila das Músicas",
    'CEP': "54321-987",
    'CNAE PRINCIPAL CODIGO': "5920001",
    'CNAE PRINCIPAL DESCRICAO': "Atividades de gravação de som e de edição de música",
    'CNPJ': "66666666000100",
    'COMPLEMENTO': "ESTÚDIO 1",
    'DATA ABERTURA': "22/05/2013",
    'DDD': "21",
    'EMAIL': "contato@estudioexemplo.com",
    'LOGRADOURO': "Rua dos Músicos, 456",
    'MUNICIPIO': "Rio de Janeiro",
    'NOME FANTASIA': "Estúdio de Gravação Musical",
    'NUMERO': "456",
    'RAZAO SOCIAL': "Estúdio de Som Exemplo Ltda",
    'SETOR': "Música",
    'STATUS': "ATIVA",
    'TELEFONE': "(21) 5555-9876",
    'TIPO LOGRADOURO': "Rua",
    'UF': "RJ",
    'ID': '7',
    },{
    'BAIRRO': "Jardim dos Sonhos",
    'CEP': "12345-678",
    'CNAE PRINCIPAL CODIGO': "9001501",
    'CNAE PRINCIPAL DESCRICAO': "Produção de filmes para cinema e vídeos",
    'CNPJ': "88888888000100",
    'COMPLEMENTO': "ESTÚDIO 5",
    'DATA ABERTURA': "10/12/2011",
    'DDD': "11",
    'EMAIL': "contato@estudiofilmesexemplo.com",
    'LOGRADOURO': "Avenida da Produção, 123",
    'MUNICIPIO': "São Paulo",
    'NOME FANTASIA': "Estúdio de Filmes Sonhos Dourados",
    'NUMERO': "123",
    'RAZAO SOCIAL': "Estúdio de Filmes Exemplo Ltda",
    'SETOR': "Cinema e Produção de Vídeos",
    'STATUS': "ATIVA",
    'TELEFONE': "(11) 5555-4321",
    'TIPO LOGRADOURO': "Avenida",
    'UF': "SP",
    'ID': '8',
    },{
    'BAIRRO': "Centro da Inovação",
    'CEP': "34567-890",
    'CNAE PRINCIPAL CODIGO': "6202300",
    'CNAE PRINCIPAL DESCRICAO': "Desenvolvimento e licenciamento de programas de computador não customizáveis",
    'CNPJ': "55555555000101",
    'COMPLEMENTO': "ANDAR 3",
    'DATA ABERTURA': "20/08/2017",
    'DDD': "47",
    'EMAIL': "contato@desenvolvedoraexemplo2.com",
    'LOGRADOURO': "Avenida da Tecnologia, 789",
    'MUNICIPIO': "Joinville",
    'NOME FANTASIA': "Tech Solutions 2.0",
    'NUMERO': "789",
    'RAZAO SOCIAL': "Desenvolvedora de Software Exemplo 2.0 Ltda",
    'SETOR': "Desenvolvimento de Software",
    'STATUS': "ATIVA",
    'TELEFONE': "(47) 5555-6789",
    'TIPO LOGRADOURO': "Avenida",
    'UF': "SC",
    'ID': '9',
    },{
    'BAIRRO': "Vila dos Estilistas",
    'CEP': "65432-109",
    'CNAE PRINCIPAL CODIGO': "7410202",
    'CNAE PRINCIPAL DESCRICAO': "Design de moda",
    'CNPJ': "77777777000101",
    'COMPLEMENTO': "ESTÚDIO 7",
    'DATA ABERTURA': "12/05/2014",
    'DDD': "81",
    'EMAIL': "contato@estilistaexemplo.com",
    'LOGRADOURO': "Rua das Tendências, 321",
    'MUNICIPIO': "Recife",
    'NOME FANTASIA': "Estúdio de Moda Fashion",
    'NUMERO': "321",
    'RAZAO SOCIAL': "Estilista Exemplo Ltda",
    'SETOR': "Moda",
    'STATUS': "ATIVA",
    'TELEFONE': "(81) 5555-1234",
    'TIPO LOGRADOURO': "Rua",
    'UF': "PE",
    'ID': '10',
    },{
    'BAIRRO': "Vila dos Artistas Plásticos",
    'CEP': "54321-987",
    'CNAE PRINCIPAL CODIGO': "9001400",
    'CNAE PRINCIPAL DESCRICAO': "Atividades de artistas plásticos independentes",
    'CNPJ': "11111111000102",
    'COMPLEMENTO': "ATELIER 4",
    'DATA ABERTURA': "25/10/2013",
    'DDD': "21",
    'EMAIL': "contato@artistaexemplo.com",
    'LOGRADOURO': "Rua das Cores, 456",
    'MUNICIPIO': "Rio de Janeiro",
    'NOME FANTASIA': "Atelier das Artes",
    'NUMERO': "456",
    'RAZAO SOCIAL': "Artista Exemplo S.A.",
    'SETOR': "Artes Plásticas",
    'STATUS': "ATIVA",
    'TELEFONE': "(21) 5555-9876",
    'TIPO LOGRADOURO': "Rua",
    'UF': "RJ",
    'ID': '11',
    },{
    'BAIRRO': "Jardim das Descobertas",
    'CEP': "12345-678",
    'CNAE PRINCIPAL CODIGO': "8542100",
    'CNAE PRINCIPAL DESCRICAO': "Atividades de ensino superior",
    'CNPJ': "99999999000102",
    'COMPLEMENTO': "SALA 10",
    'DATA ABERTURA': "30/04/2015",
    'DDD': "11",
    'EMAIL': "contato@universidadeexemplo.com",
    'LOGRADOURO': "Avenida do Conhecimento, 123",
    'MUNICIPIO': "São Paulo",
    'NOME FANTASIA': "Universidade Inovadora",
    'NUMERO': "123",
    'RAZAO SOCIAL': "Universidade Exemplo Ltda",
    'SETOR': "Educação",
    'STATUS': "ATIVA",
    'TELEFONE': "(11) 5555-4321",
    'TIPO LOGRADOURO': "Avenida",
    'UF': "SP",
    'ID': '12',
}]